name: Deploy RepoEnviosMGM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Alwaysdata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files by FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps
          timeout: 86400000
          log-level: standard
          exclude: |
            .git/**
            .github/**
            workflows/**
